# Resumen {-}
\setstretch{1.0}

Esta investigación hace uso del censo arbóreo urbano realizado en Santiago de Cali (Colombia) entre el año 2014 y 2015, de los datos del censo de población de 2005 y los datos de la estructura ecológica del municipio del 2014. El propósito es identificar si existen patrones espaciales estadísticamente significativos que den evidencia de sesgos de los indicadores de acceso a servicios ambientales del arbolado urbano (AU) y espacios verdes (EV) con indicadores socioeconómicos, con el fin de identificar espacialmente inequidades en el acceso a este tipo de servicios ecosistémicos.

Para lograrlo se hace uso de modelos de regresión espacial que capturan fenómenos de agrupamiento y dispersión en los patrones espaciales, a través la inclusión de términos de autocorrelación espacial en la regresión lineal. Los modelos espaciales de regresión se prueban con dos tipos de matrices para observar el efecto de la topología de interacción entre las variables y los resultados del ajuste. Se hace uso de gráficos estadísticos, mapas temáticos y de LISA para la identificación de zonas con concentración en el acceso. 

Los resultados muestran que existen inequidades explicadas por variables de estatus como el acceso a educación superior, que están además negativamente correlacionadas con el porcentaje de afrocolombianos en un sector censal urbano (SU). En relación al acceso a espacios verdes, no existe evidencia fuerte de que las variable de etnicidad, salud o estatus sean buenos predictores del acceso. Sin embargo, sí se encontró una alta concentración del área del EV disponible en muy pocos sectores de la ciudad. 



# Abstract {-}

\setstretch{1.0}

This study uses the urban arboreal census carried out in Santiago de Cali (Colombia) between 2014 and 2015, the data of the 2005 population census and the data of the ecological structure of the municipality of 2014. The purpose is to identify if there are spatially significant patterns that provide evidence of biases in the indicators of access to environmental services of urban trees (AU) and green spaces (EV) with socioeconomic indicators, in order to spatially identify inequities in access to these types of ecosystem services.

To achieve this, spatial regression models are used to capture grouping and dispersion phenomena in spatial patterns through the inclusion of terms of spatial autocorrelation in linear regression. The spatial models are tested with two types of matrices to observe the effect of the topology in the interaction between the variables and the results of the adjustment. Statistical graphs, thematic and LISA maps are used to identify areas with poor levels of access and discuss explanation related to the causes.


The results show that there are inequities explained by status variables such as access to higher education, which are also negatively correlated with the percentage of Afro-Colombians in an urban census sector (SU). In relation to access to green spaces (EV), there is no strong evidence that the variables of ethnicity, health or status are good predictors of access. However, there was a high concentration of the EV area available in very few sectors of the city.
