# Conclusiones {#conclusiones}

Quiero resaltar el uso de herramientas libres como *R*, Rstudio y los diferentes paquetes del ecosistema del CRAN, que favorecen la reproductibilidad y diseminación del conocimiento científico. El esfuerzo y la curva de aprendizaje de herramientas como Bookdown [R-bookdown] y knitr [@R-knitr] para la generación de los contenidos y textos en diferentes formatos,la reproductibilidad del uso de scripts y la posibilidad de publicar un repositorio del resultado, del proceso y de los datos, no solo vale la pena como base para la construcción de flujos de trabajo eficientes en el manejo y divulgación de datos e información —geográfica—, sino que me parece un compromiso ineludible  con la construcción de la ciencia de nuestro tiempo y de la ética investigativa.

En cuanto a lo metodológico en este trabajo se hizo esfuerzos por conjugar la exposición gráfica de los datos crudos y de los resultados estadísticos con la rigurosidad y capacidad explicativa de los modelos de regresión estadísticos y geoestadísticos. Entre las posibilidades que ofrece el código como herramienta cartográfica está la de producir y reproducir múltiples mapas, en lugar de uno solo con mucho detalle como respuestas a las limitaciones tecnológicas  y de costos de la cartografía impresa, lo que redunda en mejor información para los análisis. Los métodos gráficos como los mapas de LISA permiten una interpretación más clara de los mecanismos de ajuste de los modelos espaciales y de la combinación lineal de los términos. Estos mapas junto con los mapas temáticos de cada una de las variables, los gráficos de dispersión de las distribuciones multivariadas son una estrategia eficaz para lidiar con las dificultades para analizar conjuntos de datos multidimensionales y espaciales.  Los métodos de ajuste espacial y la comparación entre distintos modelos permitieron  seleccionar el resultado más confiable y eficiente de la estimación, dando firmeza a las conclusiones de los análisis.

En relación a lo temático este trabajo demuestra que en lo que respecta al acceso de beneficios del arbolado urbano en Santiago de Cali existe una fuerte relación de la variable de estatus social representada por el acceso a estudios superiores, que explica la variabilidad en los datos y los patrones espaciales de la cobertura de copa. Los modelos de regresión espacial confirman que los beneficios ambientales son mejores en sectores con población mejor educada, posiblemente una razón para preferir o habitar espacios con buena arborización o tal vez con condiciones suficientes de espacio y zonas blandas para arborizar el barrio y propiciar el desarrollo del potencial de los individuos arbóreos. En cualquier caso, esto muestra que los clusters de sectores urbanos con mayor arborización excluyen al grueso de la población afro y con bajos niveles de estudios, como prueban las altas correlaciones negativas entre los valores de estos grupos de población y  la cobertura de copa. El mapa de los beneficios ambientales se suma pues a una serie de inequidades encontradas en la literatura que aborda problemas relacionados con la segregación racial y la baja empleabilidad de poblaciones afrocolombianas en la ciudad de Cali. Los casos de análisis espacial en relación al acceso de servicios ambientales fueron descritos ampliamente en la literatura y nos muestran una preocupación creciente sobre la integración y restauración de ecosistemas urbanos, una sofisticacion metodológica y fundamentación teórica que fueron claves para aplicar exitosamente el análisis al contexto de Cali. Además coinciden en señalar problemas de segregación e inequidades ambientales en el continente americano.


En cuanto a los espacios verdes el ejercicio no es mucho más alentador. Este trabajo mostró cómo existe una importante cantidad de sectores urbanos con menos del 5% del área del sector de espacio verde: una alta concentración del área disponible se encuentra unos pocos sectores, que sirven para suplir las carencias de espacio verde en sus vecinos. Aunque el coeficiente de la dimensión poblacional representada por porcentaje de personas con alguna limitación física o mental, es bajo, coincide espacialmente con las zonas de bajo acceso a estos espacios. Sin embargo en la medición del acceso como un beneficio local las variables poblacionales no pasaron los criterios de selección para ser candidatas en el modelo de regresión. El área media de manzana de un sector fue muy representativa y significativa de la variabilidad de los datos, y señala indirectamente la responsabilidad de las autoridades y los urbanizadores que deben garantizar la provisión de los equipamientos de ciudad, los tamaños mínimos y deseados, y  en general velar por el desarrollo la estructura ecológica del municipio y del casco urbano. 

Analizar varios indicadores con variaciones en el cálculo y en las variables incorporadas en su definición permite construir una visión más compleja y detallada del acceso. Este trabajo se limitó a analizar 2 indicadores por beneficio ambiental, explorando las diferencia entre indicadores porcentuales que representan las diferencias entre medir el beneficio en el área total de un sector o sólo sobre su espacio público, para establecer una matiz entre  lo que compete a las autoridades y el alcance de un beneficio que se irradia más allá  de las  fronteras de las calles y los límite administrativos. También explora dos experiencias distintas del acceso a espacio verdes, la local, al interior de un sector urbano y otra en la escala de las agrupaciones de sectores. Resultado de esta se puede pensar explorar complejizar estos indicadores para incorporar aspectos de la calidad de los espacio o incluir dimensiones poblacionales como la densidad o normalizarlos con respecto del número de habitantes.

Más interesante puede ser contar con dos conjuntos de datos separados en el tiempo tanto de las variables poblacionales y del arbolado urbano, para indagar sobre cómo la matriz de vecindad puede capturar las variaciones de la estructura de las características poblacionales de los individuos humanos y arbóreos; o analizar el impacto de la inclusión de nuevos espacio verdes a la topología de beneficios y estimar cambios en la estructura de grupos de sectores urbanos con acumulacion de desvenajas, por ejemplo. 

Esto me lleva al último punto de las conclusiones y el primer momento dentro del proceso de esta investigación: la disponibilidad de los datos. Sin la existencias de los servicios de información geográfica de la Alcaldía de Cali ni la disposición de la cartografía del censo y los datos agregados a nivel de sector urbano del DANE, o la existencia de un censo arbóreo es imposible progresar en el entendimiento de nuestro desarrollo como ciudad, región o nación.  Sin embargo, aún son escasas las variables del censo de población que están disponibles a este nivel, no existe un repositorio público de los datos del censo arbóreo, ni de las acciones de mantenimiento y estado del arbolado urbano a pesar de que no existe ningún impedimento técnico ni legal para que pueda estarlo. Los resultados dependen pues no solo de la disponibilidad sino de la calidad y nivel de actualización de los datos, que pueden y deben mejorar en los servicios de información que presta el el municipio. 


