--- 
title: "Inequidades socioeconómicas en relación a los espacios verdes y cobertura de copa: un enfoque espacial aplicado a la ciudad de Cali, Colombia"
subtitle: "Juan Fernando Correa Caicedo"
author: 
- "Presentado para obtar al título de Maestría en SIG (M.Sc. UNIGIS)"
- "Universidad de Salzburgo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 12pt
linestretch: 1.5
toc-depth: 2
lof: True
lot: True
papersize: a4
geometry: "left=3cm, right=2.5cm, top=3cm, bottom=2.5cm"
bibliography: [tesisbck.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: correajfc/unigis-tesis
description: "Tésis para obtar al el título de Maestría en SIG (M.Sc. UNIGIS)"
---

```{r setup-chunks, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE,tidy = FALSE, out.width = '100%', cache = TRUE, fig.width = 6, warning = FALSE, message = FALSE, dpi = 150, dev = 'png')


```



# Agradecimientos {-}

A Elizabeth, Augusto, Ana María y Catalina. Este trabajo fue posible gracias a su ayuda y cariño. 


# Abreviaciones {-}

```{r abrev}
data_frame(
  Term = c("Arbolado Urbano","Espacio Verde","Sector Urbano", "*Ordinary Least-Square*",
           "*Maximum Likelihood*","Modelo Autoregresivo o *Spatial Autocorrelation*",
           "Retardo Espacial en X o *Spatial Lag*","Modelo Espacial del Error o *Spatial Error Model*",
           "Modelo Espacial de Durbin","Infraestructura de Datos Espaciales de Santiago de Cali","Plan de Ordenamiento Territorial","Estructura Ecológica Complementaria","*Web Feature Service*","Censo Arbóreo de Cali 2015","Censo de Población 2005 de Colombia","lugares Especiales de Alojamiento","*Local indicators of spatial association*"),
  Abbreviation = c("AU", "EV", "SU","OLS","ML","SAR","SLX","SEM","SD","IDESC","POT","EEC","WFS", "CA2015","CP2005","LEA","LISA")) %>%
  arrange(Abbreviation) %>% # i.e. alphabetical order by Term
  kable(booktab = T, col.names = c("Término","Abreviación"))

```




```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

