# Revisión de la literatura {#revlit}

## Las instituciones ambientales en Santiago de Cali 

Los árboles son pieza clave de los ecosistemas donde la vida humana ha prosperado. Son hogar y fuente de alimento de muchas especies [@osorio_vuelo_2009]; forman espacios con condiciones climáticas y funcionales que complejizan el paisaje y las posibles relaciones entre los animales [@chapman_forests_1998]. Se puede ubicar la década de los 70 el inicio de un pensamiento ambiental que empieza a ser relevante en el discurso económico mundial[@leff_pensamiento_2012] y que se consolida con la publicación del Informe Brundtland en 1987. Sin embargo, las preocupaciones sobre la sostenibilidad y conservación de los ecosistemas que sustentan la vida en el planeta son relativamente nuevas en la economía mundial, si la comparamos con la simbiosis entre árboles y humanos que dan origen a la agricultura y lo convierten en un elemento simbólico de gran riqueza en el universo religioso y cultural de la humanidad [@leon_calle_arboles_2011]. 
 
En Colombia fue el Instituto Nacional de los Recursos Naturales Renovables y del Ambiente (INDERENA) el pionero de la gestión ambiental, fundado en 1968 y adscrito al ministerio de Agricultura. En 1993 con la ley 99 se crea el Ministerio del Medio Ambiente (MinAmbiente), reemplazando al INDERENA que había cumplido su ciclo de vida, dando paso a esta nueva entidad fortalecida económicamente y en sintonía con la dinámica ecológica mundial (Becerra, 2012). Su homólogo municipal, el Departamento Administrativo de Gestión del Medio Ambiente (DAGMA), entidad responsable de la gestión del medio ambiente y de los recursos naturales, de la política y de la acción ambiental en la ciudad de Cali, fue creada 1996 (Acuerdo 01 de 1996).

Los ambientes naturales y estructuras ambientales de las ciudades dependen fuertemente los proyecto de urbanización y de las medidas que tomen las autoridades locales para mantenerlos y promoverlos[@konijnendijk_arboles_2005; @mincey_structuring_2013]. Investigaciones como [@dobbs_framework_2011; @ponce_donoso_valoracion_2009] expresan la importancia conformar esquemas y construir modelos de valoración y gestión de este componente del paisaje urbano. A pesar del reconocimiento de los ecosistemas urbanos en el discurso de las instituciones a nivel municipal desde hace un poco más dos décadas en Colombia, los avances en la consolidación de políticas, instrumentos de seguimiento y acciones eficaces para la gestión y de los bosques urbanos y los espacios verdes tienen grandes falencias técnicas. Por lo tanto, es clave que las autoridades establezcan directrices que orienten a los diferentes entes territoriales sobre el adecuado manejo del arbolado urbano, y avances en la consolidación de sistema de información y monitoreo [@tovar-corso_aproximacion_2013]. 

En Cali, el progreso en este tema ha sido lento, pero existe.

Con la formulación del POT2014 se estructuró un análisis que se compone de un marco legislativo, teórico, conceptual y la definición de los objetos geográficos  y zonas que componen la estructura ecológica del municipio. En el informe técnico del POT2014 se evidencia las crecientes dificultades ambientales que presenta el municipio, en particular la zona urbana, en la calidad del aire^[*“Cali es una de las capitales más contaminadas de Colombia, por debajo de Bogotá, igualando a Medellín y superando a Barranquilla, Cartagena y Pereira, según el CONPES.”* @noauthor_plan_nodate, pp. 213], el estado de las cuencas hidrográficas, contaminación auditiva^[*“La contaminación por ruido es un factor crítico en la ciudad. En todas las comunas de Cali, los niveles de ruido superan los 70 decibeles, que están por encima de los estándares permisibles fijados por la normatividad ambiental nacional vigente y la OMS (60dB)”* @noauthor_plan_nodate, pp. 215], entre otros. El agravante de esta situación es *“la inexistencia de un sistema de información y monitoreo, observatorio ambiental o sistema municipal de indicadores ambientales, asociado al Expediente Municipal (EM) ha contribuido a la deficiente gobernabilidad sobre la base ecosistémica, el deterioro del sistema ambiental, el aumento en los niveles de riesgo, y la degradación de los servicios ambientales.”* [@noauthor_plan_nodate, pp. 233]

El POT2014 construye un análisis y consolida datos que sustentan y proponen directrices sobre la estructura ecológica principal (EEP) del municipio^[*“La Estructura Ecológica Principal del municipio de Santiago de Cali está compuesta por las áreas de protección y conservación ambiental en los términos del artículo 4 del Decreto 3600 del 2007 y del artículo 35 de la Ley 388 de 1997 y se constituye como suelo de protección ambiental331, y como determinante ambiental del ordenamiento territorial de conformidad con lo establecido en el artículo 15 de la misma ley. A esta categoría pertenecen los elementos del territorio que mantienen características de composición, estructura y/o función que les permite prestar servicios ecológicos y/o ambientales y cuyas características permiten mantener los procesos ecológicos esenciales del territorio convirtiéndose en el principal componente de la Estructura Ecológica Municipal.”* @noauthor_plan_nodate, pp. 715], contenida en su mayoría por la parte rural del municipio, pero poco hay de concreto en cifras sobre la línea de base del arbolado urbano y sobre la estructura ecológica complementaria (EEC)^[*“El segundo componente de la Estructura Ecológica Municipal es la Estructura Ecológica Complementaria (EEC), y corresponde a los elementos del territorio construido que, en su mayoría, hacen parte de los sistemas estructurantes del territorio y que a pesar de su transformación cultural y de no ser de carácter estrictamente natural, mantienen características, de composición, estructura y/o función que les permite seguir prestando servicios ecológicos y/o ambientales. Las características de estos elementos les permiten fortalecer y apoyar la definición de la Estructura Ecológica Municipal y la conservación de los recursos naturales. Las áreas que pertenecen a la Estructura Ecológica Complementaria no constituyen suelo de protección, sin embargo deben mantener y/o mejorar sus características ambientales para cumplir con su aporte a la estructura ecológica del municipio.”* @noauthor_plan_nodate, pp. 715] que incluye las zonas verdes, cinturones ecológicos y los árboles de calle. Justame es el POT2014 quien en concordancia con el Estatuto Arbóreo de 2013 [@noauthor_estatuo_2013] recomienda la realización de un censo arbóreo y un diagnóstico de base para el plan de silvicultura urbana. 

El censo arbóreo fue entregado en 2015 (CA2015). Gracias a ello el Expediente Municipal (EM), instrumento encargado del seguimiento al POT, publicó avances en la consolidación de datos de medición en temas ambientales con indicadores para el área urbana agregados principalmente por comuna (ver tabla \@ref(tab:indic-ExMu)), al igual que en el informe que acompaña el CA2015 [@noauthor_informes_2015]. 

La comuna es la unidad administrativa en la cual se subdivide el área urbana de una ciudad media o principal en Colombia, agrupa barrios. 

Table:(#tab:indic-ExMu) Indicadores ambientales urbanos usados en el Expediente Municipal

|Indicador |
|------:|
|Número de árboles en zona urbana por comuna.|
|Área de copa de árboles en zona urbana por comuna.|
|Área de copa de árboles en la EEC en zona urbana por comuna.|
|Árboles por habitante en zona urbana por comuna.|
|Vitalidad de los árboles en zona urbana por comuna.|
|Árboles sembrados por comuna en el marco del proyecto 1865 de la CVC.|


La Organización Mundial de la Salud (OMS) recomienda que una ciudad tenga un árbol por cada tres habitantes, incluyendo espacios públicos y privados. Cali debería tener una población arbórea cercana a los 800.000 árboles, pero de acuerdo con los resultados del censo arbóreo de 2014–2015, se han contabilizado cerca de 290.000 árboles solo en el espacio público^[Suele ser fina la diferenciación de este término entre los urbanistas. ]. La siembra de 20.000 árboles en la zona urbana, en las comunas que muestran temperaturas por muy por encima de la media (las comunas 3, 4, 5, 8 y 13) propuesta en [@ciat_identificacion_2015] contrasta con los 100.000 árboles que tiene como meta en Plan de Desarrollo Municipal 2016-2019; ambas cifras están lejos de impactar el déficit arbóreo de 500.000 individuos; urge la reforestación, *“sin embargo, la ubicación de los sitios de siembra ha sido uno de los principales inconvenientes del proyecto, ya que no existen zonas de espacio público adecuadas o disponibles para tal fin.”* [@ciat_identificacion_2015, p. 19]

El otro instrumento consignado en el Estatuto Arbóreo de 2013 [@noauthor_estatuo_2013] para la reforestación es el esquema de compensación por intervención del arbolado urbano, que tiene un método de cálculo para la compensación por tala, traslado e intervenciones, pero no dice como se ubicaran las zonas de siembra y compensación. La tala, poda de árboles y el corte de pastos de las zonas verdes son en gran medida las actividades de gestión que ha realizado históricamente el DAGMA; las labores de fumigación y mantenimiento preventivo como el control de plagas o fertilización son actividades esporádicas, escasas y contingentes.

## Árboles y desarrollo urbano 

El hombre ha materializado espacios urbanos con dimensiones que retan la imaginación y llevan al límite los sistemas de infraestructura, abastecimiento y gobernabilidad. En la empresa de consolidar antroposferas, las ciudades que construimos han desplazados muchos de los ecosistemas naturales de los territorios que fueron la razón de escoger justamente esos sitios para el asentamiento, trasladándolos más allá de los límites de la ciudad, atenuando su presencia/visibilidad en el mundo de los ciudadanos. Son reemplazados por vías, zonas verdes, áreas industriales, comerciales y residenciales[@azocar_urbanization_2007].

El desarrollo urbano de Cali se fue dando en forma de barrios. Cali entra al siglo XX con unos de 25000 habitantes y una 100 hectáreas [@vasquez_historia_1990]; en 2005 tiene una población  2200000 habitantes según el Censo de Población del 2005 y una área urbana 12.101.326 hectáreas. Durante todo este siglo experimenta un rápido crecimiento demográfico, rápida expansión y crecimiento de la vivienda por las migraciones, causadas en gran medida por los fenómeno de desplazamiento por conflictos en las áreas rurales y el fortalecimiento de la industria y el empleo en las ciudad [@vasquez_historia_1990]. Los barrios se desarrollaron no sólo como unidades de crecimiento urbano con características físicas diferenciadas por los diseños de las constructoras según el tipo de viviendas y las capacidades económicas de la población; la ciudad creció con la especulación de la tierra de las familias adineradas de la región que fueron parcelando sus latifundios para su urbanización.

## Servicios ecosistémicos y su valoración 

Las preocupaciones sobre el crecimiento de la población mundial, su concentración en centros urbanos y las transformaciones que trae consigo el proceso de cambio climático, nos obligan a pensar en cómo maximizar los beneficios que nos brindan las zonas verdes y el bosque urbano como estrategia para mitigar los efectos negativos de estos procesos [@nesbitt_exploring_2016;  @laredo_gestion_2011]. A este escenario se suma trabajos como [@nowak_tree_2012] que revelan patrones de decaimiento estadísticamente significativos del arbolado urbano en 17 de  20 ciudades norteamericanas o [@restrepo_incidence_2015] que reporta la reducción de las condiciones de vitalidad del arbolado del Valle de Aburra en Colombia derivado de la interacción de causas naturales y antrópicas, las cuales afectan directa o indirectamente la fisiología y salud de los árboles en los espacios urbanos. @nowak_tree_2012 se pregunta si los administradores locales conocen los cambios que presenta las coberturas arbóreas, puesto que esta es una representación simple pero confiable (y ampliamente aceptada) para tasar la extensión de los beneficios derivados de los bosque urbanos, dado que los servicio que proveen los árboles están relacionados con la salud y el funcionamiento de sus hojas. 

Podemos definir un servicio ambiental o ecosistémico como los beneficios para la población humana que se derivan directa o indirectamente de los ecosistemas [@bolund_ecosystem_1999]. Los servicios dependen entonces de los tipos de los ecosistemas con los que cuente el entorno urbano. @bolund_ecosystem_1999 distinguen 7 tipos de ecosistemas urbanos: árboles de calle, zonas verdes, bosques urbanos, tierras cultivadas, humedales, lagos/lagunas, y ríos/arroyos. Todos ellos en conjunto benefician a la población, y muchos estudios se han encargado de cuantificar el impacto de estos beneficios, en particular se cuentan los que se relacionan con los ecosistemas de árboles de calle y las zonas verdes, como reducción de las temperaturas [@ripoll_condiciones_2010], reducción de la polución en el aire [@duran_rivera_intercepcion_2009], secuestro de carbono [@nowak_carbon_2002; @mcpherson2013new] , mitigación de los efectos de calentamiento por gases de efecto invernadero [@laredo_gestion_2011] y mantenimiento del agua en los ecosistemas o proveyendo alimento como en el caso de los árboles frutales [@konijnendijk_arboles_2005;@nolazco_diversidad_2012],  reducción de los niveles de ruido [@bolund_ecosystem_1999]. Otros estudios argumentan que los beneficios ambientales de los ecosistemas urbanos pueden medirse directamente en la salud de la población [@bolund_ecosystem_1999;@gomez-baggethun_classifying_2013]. Una forma de clasificar todos estos beneficios e indagar sobre las medidas usadas las resume @gomez-baggethun_classifying_2013 en una tabla que reproduzco a continuación (ver tabla \@ref(tab:clasf-SerAm)).


Table:(#tab:clasf-SerAm) Clasificación de servicios ecosistémicos importantes en zonas urbanas y funciones y componentes subyacentes del ecosistema

|Funciones y componentes|Servicio Ecosistémico|Ejemplo|Ejemplo de indicadores/proxies|
|-----------------------:|-------------------:|----------------:|-------------------:|
|Conversión de energía en plantas comestibles a través de la fotosíntesis|Suministro de alimentos|Hortalizas producidas por lotes urbanos y áreas periurbanas|Producción de alimentos [toneladas/año]|
|Percolación y regulación de la escorrentía y la descarga del río|Regulación del caudal de agua y mitigación de escorrentía|El suelo y la vegetación percolan el agua durante eventos de precipitación intensa y / o prolongada|Capacidad de infiltración del suelo; [%] Sellado con respecto a la superficie permeable [ha]|
|Fotosíntesis, sombreado y evapotranspiración|Regulación urbana de la temperatura|Los árboles y otra vegetación urbana proporcionan sombra, crean humedad y bloquean el viento|Índice de área foliar; Disminución de la temperatura [° C] por cobertura arbórea[m2] en parcelas cubierta de árboles|
|Absorción de ondas sonoras por la vegetación y el agua|Reducción de ruido|Absorción de ondas sonoras por barreras vegetales, especialmente vegetación espesa|Superficie de la hoja [m2] y distancia a las carreteras [m]; Reducción de ruido [dBA] / unidad de vegetación [m]|
|Filtración y fijación de gases y partículas|Purificación de aire|Eliminación y fijación de contaminantes por la vegetación urbana en hojas, tallos y raíces|O3, SO2, NO2, CO y PM10 μm removido en [toneladas/año] multiplicado por la cobertura arbórea (m2)|
|Barrera física y absorción en energía cinética|Moderación de los extremos ambientales|Tormentas, inundaciones y amortiguación de olas por barreras vegetales; Absorción de calor durante olas de calor severas|Cubrir la densidad de las barreras de vegetación que separan las áreas construidas del mar|
|Eliminación o descomposición de nutrientes xénicos|Tratamiento de desechos|Filtración de efluentes y fijación de nutrientes por humedales urbanos|P, K, Mg y Ca en mgkg-1 en comparación con las normas de calidad del suelo y del agua|
|Secuestro y fijación de carbono en la fotosíntesis|Regulación climática|Secuestro y almacenamiento de carbono por la biomasa de arbustos urbanos y de tres|Secuestro de CO2 por árboles (carbono multiplicado por 3.67 para convertir a CO2)|
|Movimiento de los gametos florales por la biota|Polinización y dispersión de semillas|El ecosistema urbano provee hábitat para aves, insectos y polinizadores|Diversidad de especies y abundancia de aves y abejorros|
|Ecosistemas con valores recreativos y educativos|Recreación y desarrollo cognitivo|Los parques urbanos ofrecen múltiples oportunidades para la recreación, la meditación y la pedagogía|Superficie de los espacios públicos verdes [ha / habitante (o cada 1000 habitantes)]|
|Disposición del hábitat para las especies animales|Avistamiento de animales|El espacio verde urbano proporciona un hábitat para las aves y otros animales a los que les gusta ver|Abundancia de aves, mariposas y otros animales valorados por sus atributos estéticos|

Existen diferentes perspectivas para la evaluación de los servicios ecosistémicos, en razón de ellos se crean diferentes indicadores, métodos estadísticos y metodologías para capturar de forma directa o indirecta los beneficios ambientales. [@gomez-baggethun_classifying_2013] propone 2 tipos de valoración: la económica y la sociocultural. La valoración sociocultural se enfoca en la percepción y preferencias de los ciudadanos que están ligadas a sus costumbres y sistemas de valores. Resalta lo difícil de medir y que suele ser mejor abordado por instrumentos cualitativos, construcción de escalas y el uso de narrativas. Un ejemplo de este tipo de trabajos es  [@garzon2004vegetacion] se hace referencia a la vegetación en las ciudades y su incidencia en la vida de las personas, sobre todo en aquellas comunidades de menores recursos. “Los árboles están estrechamente vinculados a la historia de la humanidad; están cargados de historia, son testigos de varias generaciones, que enlazan su existencia con la anterior, constituyéndose en documentos vivos de acontecimientos culturales.” [@ferro_medina_arboles_2010].
[@konijnendijk_arboles_2005] propone además que se valore lo ambiental, la biodiversidad y sostenibilidad por su carácter fundamental en la existencia misma del los ecosistemas. 

Las metodologías de valoración económica se basan principalmente en análisis costo beneficios(ACB) que buscan un aprovechamiento eficiente del uso del suelo [@bolund_ecosystem_1999]. La inversión en el arbolado urbano y las zonas verdes arroja resultados positivos consistentemente en la literatura p.e [@mcpherson_quantifying_1997] reporta que los beneficios exceden los costos en ciudades como Chicago y en Adelaide (Australia) según [@killicoat_economic_2002] cada árbol da beneficios por AUD$172. 

Algunos análisis no se limitan a evaluar el costo de ahorro o el dispuesto a pagar por la población, para valorar económicamente los servicios ecosistémicos se basan en modelos biofísicos de los individuos arbóreos e incluyen variables ambientales, características de lo suelos, la infraestructura de las zonas y sus habitantes [@nelson_modeling_2009] p.e el modelo UFORE [@nowak_urban_2000] o CBAT [@mcpherson_quantifying_1997] , y que permiten tomar acciones específicas sobre el tipo de vegetación y su distribución.  Sin embargo es importante tener en cuenta que este tipo de análisis pueden generar incentivos para la conversión indeseable de ecosistemas urbanos en infraestructura construida, con la consiguiente pérdida de servicios de los ecosistemas [@gomez-baggethun_classifying_2013]. 

La lógica económica de los servicios ecosistémicos puede conducir también a incentivar procesos paradójicos, como el incrementos de los precios de las casas y arriendos que derivan en procesos de gentrificación y desplazamiento de la población que fue beneficiada por la estrategias de mejoramiento de EV y AU con el propósito de resolver problemas relacionados con la justicia ambiental. [@wolch_urban_2014]

## La perspectiva de la justicia ambiental

La justicia ambiental es un concepto que ha evolucionado desde su aparición en la década de los 1980 a través de organizaciones dedicadas al activismo ambiental y las redes que ellas forman en conjunto con la academia, acuñaron conceptos de ecología política como justicia ambiental, deuda ecológica, epidemiología ambiental, racismo ambiental, justicia climática, soberanía alimentaria, y responsabilidad ambiental empresarial, que han sido adoptados también por académicos y por tomadores de decisiones [@martinez_alier_between_2014; @cerda_origen_2011]. 

La planeación urbana, las relaciones entre los ciudadanos con los espacios públicos y con las instituciones que los rigen son la base de la idea de justicia ambiental propuesta en [@low_public_2013], y que tiene 3 componentes que la definen: *i)* la justicia distributiva, que en términos de espacio público se basa asegurar disponibilidad y acceso equitativo de los espacios y servicios a los ciudadanos; *ii)* la justicia procedimental o procesal, que se refieren a los procesos de negociación y toma de decisiones, en concreto a la percepción de los individuos sobre qué tan justos y equilibrados son, y por tal motivo más dispuesto a aceptar los resultados aunque no les favorezca; *iii)* la justicia interaccional, que refiere al comportamiento y trato de la personas en el espacio público que configuren comportamiento violento o discriminatorios sobre grupos de la población. El autor argumenta que las condiciones ambientales provocadas por los procesos de urbanización y/o contaminación deben analizarse pensando en satisfacer las tres dimensiones, de lo contrario no es posible hablar de justicia. [@schlosberg_theorising_2013] lleva la reflexión un poco más lejos, argumentando que las nuevas extensiones de la justicia ambiental se han movido del discurso a un nuevo dominio, donde lo natural y ambiental crean las condiciones para la justicia social. 

En [@braverman_everybody_2008] se exploran las implicaciones entre las intervenciones en el arbolado urbano y el control de fenómenos como el crimen y la gobernabilidad dada las relaciones afectivas y morales de la población con los árboles. El uso de los árboles puede verse también una forma de discriminación y de discurso político o tecnología de gobierno. El uso de zonas verdes y arboles ha sido usado también como una forma de simbolica de estatus y de poder, y esta afirmación es consistente que la tendencia en tener distribuciones inequitativas [@braverman_everybody_2008].

La perspectiva distributiva de la justicia ambiental busca relacionar entonces métricas usadas para cuantificar los servicios ecosistémicos con métricas sobre la población y sus condiciones de vida usando unidades espaciales para caracterizar su comportamiento en el área de estudio.Típicamente se usan variables ambientales que representan aspectos biofísicos de los ecosistemas p.e superficie de la hoja, índice de área foliar, el área de cobertura de la copa o los efectos directos e indirectos de los ecosistemas sobre variables climáticas p.e temperatura o humedad, o físico-químicas para representar la composición del suelo y del aire, o mediciones de la capacidad de secuestrar carbono de los árboles y la de filtrar agua del suelo.

Los primeros trabajos enmarcados en la justicia ambiental se enfocaron en la ubicación de plantas de residuos y manejo de desechos relacionándolos con variables sociales como la etnicidad e indicadores de segregación racial o en comunidades con bajos ingresos [@heynen_political_2006]y que desarrollan trabajos  como [@chakraborty1997exploring; @cutter_role_1996]. Posteriormente con el avance de modelos y tecnologías de la información para la caracterización de la infraestructura ecológica urbana y la cuantificación de servicios ambientales se desarrollan metodologías para establecer relaciones entre distribuciones desiguales adoptando el uso de la cobertura de copa de los árboles como variable que se consolida para este tipo de estudios, con variables socioeconómicas principalmente de raza/etnicidad de la población, que tradicionalmente ha sido una preocupación en el estudio de las desigualdades sociales [@heynen_political_2006; @landry_street_2009; @phelps_association_2012; @zhou_social_2013; @schwarz_trees_2015; @watkins_is_2016].

De los espacios verdes suelen caracterizarse dimensiones sobre el acceso, su dimensiones físicas, los equipamientos y servicios que prestan, y si los beneficiarios de  son del ámbito local al EV o más amplio. Igualmente es importante preguntarse por la calidad del parque y zonas verdes así como los uso, que pueden variar dependiendo de las comunidades que están disfrutando del parque [@kabisch_green_2014]. El acceso suele ser un concepto complejo de medir, pues el análisis espacial de los datos arroja variaciones significativas usando diferentes métricas que proviene de los diferentes conceptos de acceso usados para su definición [@talen_assessing_1998].

En Cali se han realizado trabajos que caracterizan procesos de desigualdades entre la población analizando factores como la segregación racial, brechas salariales,  empleabilidad e índices socioeconómicos de segregación espacial[@arroyo_mina_afrocolombianos_2016; @mora_brechas_2014; @ceron_indice_2014].  Aunque todos ellos incluyen una dimensión espacial, en tanto que usan las comunas como unidades de agregación de las variables socioeconómicas, su análisis no hace uso de los datos espaciales de los objetos geográficos, su base teórica son los modelos econométricos de regresión de mínimos cuadrados o la creación de índices (escalas) para clasificar las unidades gráficas con la escala p.e [@ceron_indice_2014] que hace uso del escalograma de Guttman, un método para normalizar las diferentes escalas usando igual número de rangos discretos y construir un índice acumulativo de todas las dimensiones.  @mora_brechas_2014 estudian la discriminación, tanto racial como por sexo a través de los modelos econométricos de Oaxaca-Blinder usado para analizar las diferencias salariales entre dos grupos usando una función que tiene un componente de discriminación. Para incluir en la ecuación la procedencia se crean los conglomerados a priori y se agregan dummies por conglomerado de comunas en la ecuación. @arroyo_mina_afrocolombianos_2016 evalúan la calidad del empleo bajo el supuesto de ser buen proxy de la calidad de vida y encuentra que en Cali existe evidencia de que las poblaciones afro son discriminadas laboralmente, y que esta discriminación está explicada por el lugar de residencia. Sin embargo, el método usado es similar al de [@mora_brechas_2014] e inclusive usa los mismo conglomerados para las variables dummies de la procedencia.

Los pocos estudios que se han llevado a cabo sobre segregación espacial y socioeconómica muestran que la exclusión de grupos étnicos en Cali tiende a coincidir espacialmente con la segregación de los grupos socioeconómicos de estratos bajos [@ceron_indice_2014]. Tendencia que también se ven estudios de ciudades norteamericanas [@heynen_political_2006;@landry_street_2009; @zhou_social_2013; @nesbitt_exploring_2016]. Quizá el mapa de distribución de los árboles y los espacios verdes se sume a las inequeidades que acumluan los habitantes de ciertas zonas de la ciudad, y este trabajo aporte a la utilización de modelos provenientes de la estadística espacial.

## Modelamiento y análisis espacial de variables ambientales y sociales

Las fuentes de datos con información espacial usada para capturar variables ambientales relacionadas con la vegetación provienen principalmente de imágenes satelitales[@landry_street_2009; @troy_predicting_2007; @vasquez_fuentes_vegetacion_2008; @nesbitt_exploring_2016], imágenes aéreas [@azocar_urbanization_2007; @heynen_political_2006; @tratalos_urban_2007], datos de Lidar [@shanahan_socio-economic_2014; @schwarz_trees_2015]  e inventarios producidos por muestras o censos arbóreos y de espacios verdes [@comber_using_2008; @killicoat_economic_2002; @nowak_urban_2000, @nowak_carbon_2002; @talen_assessing_1998]. Las imágenes satelitales son usadas en gran cantidad de los estudios dadas su creciente disponibilidad y la frecuencia de actualización —Landsat 8 revisita un mismo punto sobre la superficie de la tierra cada 16 días con un desfase de 8 días con respecto al satélite Landsat 7—, lo que permite hacer monitoreo y seguimiento a escalas entre los 15 m a 100 m por ancho de píxel. Los indicadores de cobertura calculados con base en datos de imágenes satelitales son estimados usando la escala de resolución de la imagen en combinación con el índice de Vegetación de Diferencia Normalizada (NDVI) que permite diferenciar entre densidad y tipo de vegetación leñosa o vegetación herbosa [@nesbitt_exploring_2016].

El uso de inventarios arbores permite estudios más detallados sobre las características del arbolado y son usados para evaluar la salud y estructura de los individuos arbóreos y las capacidades específicas de las especies para proveer servicios ambientales.   [@killicoat_economic_2002; @nowak_carbon_2002; @cowett_methodology_2014]. 

Entre los distintos indicadores desarrollados para capturar la extensión y distribución de los servicios ambientales la cobertura de copas ha probado ser sensible y eficaz para cuantificar hasta qué punto los árboles y bosques están proporcionando servicios críticos a los residentes [@nowak_sustaining_2010]. Se usan otros indicadores además de la cobertura en la literatura, y en muchas ocasiones se normalizan los valores de las variables ambientales por unidad de área, usando unidades geográficas definidas e introduciendo métricas sobre la densidad y cantidad de población beneficiada en el cálculo. De hecho [@cowett_methodology_2014] propone que para analizar con precisión la distribución espacial de los árboles de las calles y los beneficios que proporcionan es importante migrar hacia métricas en las que las especies arbóreas y el tamaño del árbol sean un factor en el cálculo, pues la mayoría de los servicios de los ecosistemas arbóreos son proporcionales a la cantidad de área superficial de la hoja; en esta medida las especies de árboles de mayor estatura típicamente proporcionan muchos más beneficios que las especies de menor estatura. Trabajos como [@alanis_estructura_2014] usan indicadores ecológicos de las especies como abunadancia, dominancia y frecuencia para contruir indices de importancia para valorar las especies nativas y estructura de los bosques urbanos, cuya conservación tambien hace parte de las metas de manejo del AU [@nowak_sustaining_2010].

La tabla \@ref(tab:ind-AU) resume los indicadores para cuantificar servicios/beneficios y estado de los ecosistemas arbóreos usados en la literatura revisada.  

Table: (#tab:ind-AU) Métricas para caracterizar servicios del AU 

| Metrica | Referencia |
|------------------------------------------:|----------------------:|
|Producción de alimentos [toneladas/año]|[@gomez-baggethun_classifying_2013]|
|Índice de área foliar|[@gomez-baggethun_classifying_2013]|
|Disminución de la temperatura [° C] por cobertura arbórea[m2] en parcelas/sitios cubiertas de árboles|[@gomez-baggethun_classifying_2013]|
|Superficie de la hoja [m2]|[@gomez-baggethun_classifying_2013]|
|O3, SO2, NO2, CO y PM10 μm removido en [toneladas/año] multiplicado por la cobertura arbórea (m2)|[@gomez-baggethun_classifying_2013]|
|Secuestro de CO2 por árbol (carbono multiplicado por 3.67 para convertir a CO2)|[@gomez-baggethun_classifying_2013]|
|Abundancia (por especie) [individuos]|[@alanis_estructura_2014]|
|Densidad [individuos/m2]|[@nowak_sustaining_2010]|
|Cobertura de copa de árbol por persona[m2/persona]|[@nowak_sustaining_2010]|
|Cobertura de copa de árbol[m2]|[@nowak_sustaining_2010] y muchos antes también|
|porcentaje de cobertura de copa de árbol en un área|[@nowak_sustaining_2010]|
|Dominancia de una especie en función a la cobertura de copa [m2/ha]|[@alanis_estructura_2014]|
|Dominancia relativa de la especie i respecto a la dominancia total|[@alanis_estructura_2014]|
|Frecuencia absoluta de una especie (porcentaje de presencia en los sitios)|[@alanis_estructura_2014]|
|Abundancia relativa de la especie i respecto a la abundancia total en el área de estudio|[@alanis_estructura_2014]|
|Árboles por habitante|POT2014|
|índice de cobertura de copa de árbol al rededor de un punto de muestreo|[@zhou_social_2013]|
|Porcentaje de cobertura de copa de árbol en servidumbres y espacios públicos|[@landry_street_2009]|

En cuanto a los espacios verdes se valoran típicamente los aspectos geométricos y el acceso. Los aspectos físicos se caracterizan con medidas de superficie de los espacios, el porcentaje de área o número de espacios respecto de las unidades espaciales del análisis; este tipo de medidas son llamadas por [@talen_assessing_1998] la aproximación contenedor (como el representado en la ecuación \@ref(eq:contenedor)), y aunque muy extendidas en la literatura para caracterizar acceso a los EV asumen que los beneficios del espacio verde tiene un impacto local: *“Sin embargo, si el investigador está seguro de que la esfera de influencia de un servicio dado se limita a un límite geográfico específico, puede seguir siendo apropiado el enfoque unidimensional tradicional de la accesibilidad por medio de conteos por unidad”* [@talen_assessing_1998]. En esta misma línea, [@kabisch_green_2014] asegura que aunque el secuestro de carbono tiene beneficios a nivel de toda la ciudad, algunos procesos biofísicos que rigen lo beneficios de los EV ocurren a nivel local. Aunque no es fácil definir la escala a la que operan los procesos biofísicos, los beneficiarios de los servicios ambientales son a menudo aquellos que viven cerca de los EV.

Respecto de las unidades espaciales de agregación de las variables [@cutter_role_1996] encontró que el coeficiente de correlación tiende a aumentar con el aumento de la escala de las unidades espaciales de agregación. Para verificar la robustez de las estimaciones de correlación entre la cantidad de instalaciones tóxicas/desperdicios e indicadores socioeconómicos @cutter_role_1996 usó pruebas de hipótesis para probar que tanto explican los indicadores de etnia y de ingreso la presencia de las instalaciones, agregando los datos a diferentes escalas de la cartografía censal en EE.UU (condado > sectores > bloque). Los resultados sugieren que los sectores y bloques son la escala espacial más apropiada para evaluar las desigualdades debido a las alta variabilidad de los indicadores socioeconómicos dentro del condado en comparación con los sectores y los bloques.

Estos a hallazgos ponen en cuestión la selección del tamaño de la unidades espaciales del análisis en relación con el área de estudio. Para el caso de Cali se suele usar las comunas como unidad espacial, pues es la unidad sobre la que se define la inversión, pero puede no representar muy bien la escala de los procesos que dominan las transformaciones en el AU y el acceso a los espacio verdes cuando se presenta alta variabilidad de los indicadores socioeconómicos y ambientales.

En esta línea es interesante analizar variables que capturan aspectos físicos de la estructura del espacio disponible. [@landry_street_2009] relaciona las coberturas con las áreas de los sectores censales completos y los compara con las áreas de espacio público sin los lotes de las manzanas de cada sector censal, introduciendo un indicador espacial que apunta a espacios donde la responsabilidad es claramente de la instituciones estatales por el énfasis en el área de jurisdicción para la intervención de la estructura arbórea y de los espacios verdes (ver tabla \@ref(tab:ind-AU)). 

Además de las medidas de superficie y sus variantes para caracterizar los beneficios en una unidad espacial definida, se usan medidas que relacionan origen destino, como la distancia mínima del centroide de la unidad espacial al borde del EV más cercano, que proporciona una estimación fiable de la distancia media desde cualquier punto dentro de una unidad de análisis. Este método trata a todos los espacios verdes por igual, independientemente del tamaño y la propiedad [@nesbitt_exploring_2016].

Para medir el acceso se pueden usar medidas de distancia, que operan bajo el concepto de costo de viaje. Una forma es calcular la suma de las distancias desde el centroide de una unidad espacial a **todos** los EV, como lo hace la ecuación \@ref(eq:costoviaje) y su variante \@ref(eq:ncosto) que divide el costo de viaje entre el número de EV [@talen_assessing_1998]. Una alternativa a la suma de distancias es usar la distancia del centriode al espacio verde más cercano (ecuación \@ref(eq:mindist)). Otra métrica relevante de acceso es la distancia de red a través de la estructura de las vías de la ciudad o distancia a pie, que produce una versión más realista de la experiencia de acceso, y puede usarse para calcular la distancia mínima promedio de puntos aleatorios o para cada manzana, por ejemplo, dentro de una unidad de espacial. Estas métricas exigen marcar los puntos de acceso a las zonas verdes, tarea que se realiza de forma no automática [@zhou_social_2013]. 


*índice contenedor*
\begin{equation}
A^{C}_i =\sum_j{s_j} \;  \; \forall  j \in I
(\#eq:contenedor)
\end{equation}
 

*costo de viaje*
\begin{equation}
A^{T}_i =\sum_j{d_{ij}} \; 
(\#eq:costoviaje)
\end{equation}

*costo de viaje normalizado*
\begin{equation}
\bar{A}^{T}_i =\sum_j{d_{ij}/N}
(\#eq:ncosto)
\end{equation}

*distancia mínima*
\begin{equation}
A^{M}_i=min\left | d_{ij} \right | 
(\#eq:mindist)
\end{equation}

*índice de accesibilidad a pie*
\begin{equation}
A^{W}= \sum_{\int R_b }{(r_{min}/d_j)}  \;  \; \forall  d_j>0 \; , \; r_{min}<R_b  \;
(\#eq:walkdist)
\end{equation}



El cálculo de estos indicadores e índices de acceso se ha complejizado con base en recomendación de las agencias ambientales que definen valores de referencia como la cantidad de EV mínimo disponible ( 2 ha ) en un radio determinado (300m). Esto puede lograrse, por ejemplo, con la suma de los cocientes entre el radio recomendado y la distancia de un punto de muestreo dentro de la unidad espacial a cada uno de las EV en el radio de búsqueda $R_b$, que suele ser mayor que la distancia de acceso recomendada $r_{min}$. Se pueden seleccionar un número de muestras para cada unidad espacial y sumar o promediar las distancias obtenidas  [@zhou_social_2013]  o usar el centriode como único punto (ecuación \@ref(eq:walkdist)). Modificaciones a este índice pueden incluir el área de la zona verde para cuantificar el acceso y las características del EV al que se accede [@comber_using_2008].


El tipo de espacios usualmente aceptados como espacio verde urbano en los estudios incluyen parques y jardines públicos, corredores verdes (por ejemplo, adyacentes a ríos y canales), reservas naturales locales, áreas comunes, pequeñas áreas de bosques con sotobosque, sitios de importancia para la conservación de la naturaleza, áreas de drenaje (es decir, áreas regularmente inundadas cercanas a los ríos), cementerios, instalaciones desocupadas cubiertas de vegetación, lagos y humedales, campos de golf, áreas privados de asociaciones de propietarios, terrenos escolares, parcelas y hasta senderos que no son lo suficientemente grandes para calificar como parques[@nesbitt_exploring_2016; @comber_using_2008; @kabisch_green_2014; @zhou_social_2013]. 

La tabla \@ref(tab:ind-EV) resume los indicadores usados en la literatura revisada sobre el acceso a EV.

Table: (#tab:ind-EV) Métricas para caracterizar servicios del EV

| Métrica | Referencia |
|------------------------------------------:|----------------------:|
|Superficie de los espacios públicos verdes [ha]|varios|
|Número de instalaciones o servicios contenidos en una unidad dada (por ejemplo, distrito censal o división político-administrativa)|[@talen_assessing_1998]|
|Potencial de la gravedad|[@talen_assessing_1998]|
|Distancia al EV más cercano[m]|[@talen_assessing_1998]|
|Coste medio de viaje EV más cercano|[@talen_assessing_1998]|
|Superficie de los espacios públicos verdes por habitante (o cada 1000 habitantes)[ha/habatiantante]| |
|Cobertura de espacios verdes[%]|varios|
|Distancias entre puntos o nodos en la red de movilidad urbana|[@comber_using_2008]|
|Índice de accesibilidad caminando al parque dentro de un radio|[@zhou_social_2013]|


Para la caracterización de las condiciones de vida de la población en relación con el disfrute a servicios ambientales los indicadores sociales usados suelen provenir de los censos de población, encuestas de trabajo o calidad de vida, registros catastrales para el avalúo de predios y uso de los suelo. La tabla \@ref(tab:ind-SoEc) resume algunos de los indicadores socioeconómicos usados para la evaluación de inequidades ambientales en la revisión de la literatura realizada.

Table: (#tab:ind-SoEc) Métricas para caracterizar aspectos socioeconómicos de la población y estructura de las unidades espaciales del EV

| Métrica | Referencia |
|------------------------------------------:|----------------------:|
|Ingreso medio del hogar|varios|
|Valor medio vivienda ocupada por el propietario|[@cowett_methodology_2014]|
|Porcentaje de viviendas ocupadas|[@cowett_methodology_2014]|
|Porcentaje de población blanca|[@cowett_methodology_2014]|
|Porcentaje de personas con pregrado|[@cowett_methodology_2014]|
|Porcentaje de población afro|[@cowett_methodology_2014]|
|Porcentaje de viviendas arrendadas|[@heynen_political_2006]|
|Densidad de población [residentes/ha]|[@troy_predicting_2007]|
|Densidad de hogares[hogares/ha]|[@troy_predicting_2007]|
|Valor medio vivienda ocupada|[@troy_predicting_2007]|
|Porcentaje de viviendas desocupadas|[@troy_predicting_2007]|
|Índice de delincuencia|[@troy_predicting_2007]|
|Porcentaje de viviendas que son viviendas unifamiliares|[@troy_predicting_2007]|
|Tamaño medio del hogar|[@landry_street_2009]|
|Tamaño medio del lote de vivienda|[@shanahan_socio-economic_2014]|
|Densidad de viviendas||
|Grados escolares cursados[años]||
|Porcentaje de habitantes con grado profesional|[@nesbitt_exploring_2016]|
|Porcentaje de habitantes con maestría|[@nesbitt_exploring_2016]|
|Edad del barrio||
|Edad media de las construcciones|[@zhou_social_2013]|

### Enfoque estadístico

El instrumento matemático más popular para establecer relaciones de dependencia y asociación entre dos variables aleatorias son los índices de correlación, sin que la relación cuantificada sea necesariamente de causalidad. La causalidad entre las variables suele ser una apuesta del investigador y de su conocimiento o intuición sobre los procesos que dominan las características de las variables aleatorias [@gibbons_mostly_2012]. El coeficiente de correlación de Pearson es medida usada para caracterizar la fuerza de relaciones lineales, mientras que coeficientes de correlación como el de Spearman son usados para encontrar relaciones no necesariamente lineales, pues se calcula observando si los cambios en una de las variables está relacionado con incrementos o decrementos de la otra, lo que permite cuantificar dependencias no lineales. Estos coeficientes son análisis eficaces para seleccionar variables candidatas a ser incluidos en modelos de regresión, tanto para seleccionar las variables que tienen relación fuerte con la variable a predecir, como la independencia lineal de las variables explicativas, condiciones necesarias para que los métodos de ajuste de parámetros de los modelos lineales [@gibbons_mostly_2012]. Los coeficientes de correlación, como estadística de resumen, no pueden reemplazar el examen visual de los datos y la construcción de relaciones que tengan un fundamento teórico. 

Los modelos de regresión lineal son ampliamente usados en la econometría para construir modelos explicativos con términos que describen componentes teóricos de los procesos de estudio e inferir el comportamiento o tendencias en una población con base en una muestra. De esta forma se pretende cuantificar el cambio de la variable dependiente ($y$) ante aumentos o disminuciones del valor de una de las $p$ variables dependientes $x_j$ donde $j =1...p$. Cada una de las observaciones $i$ , $i=1...n$ del vector $X_p$ denominadas $x_{ij}$ forman un sistema de ecuaciones lineales donde el parámetro $\beta_j$ pesa el aporte explicativo de la variable correspondiente al estimarlo (ecuación \@ref(eq:lmodel) y \@ref(eq:lmodelM)). Así, los coeficientes estimados representan la importancia de una variable independiente en los cambios de la dependiente. Los métodos para resolver son estimadores  de mínimos cuadrados (OLS ordinary least-square) o de máxima verosimilitud (ML maximum likelihood).  Si se cumple que las variables independientes del modelo y los términos del error tienen una distribución normal y una varianza constante (homocedasticidad), entonces el estimador es óptimo entre todos los estimadores no sesgados lineales y no lineales. Es clave indagar el cumplimiento de las condiciones de normalidad, en especial en los residuos. [@gibbons_mostly_2012].  

modelo lineal de la i-esima observación
\begin{equation}
y_i=\beta_0+ \beta_1\cdot  x_{i1}+...+\beta_j\cdot  x_{ij}+...+\beta_p\cdot  x_{ip}+e_i
(\#eq:lmodel)
\end{equation}

forma matricial del sistema de ecuaciones a resolver
\begin{equation}
Y_{n\times 1}=X_{n \times p }\mathbf{\beta}_{p\times 1}+e_{(n\times 1)}
(\#eq:lmodelM)
\end{equation}

Estudios como [@heynen_political_2006; @vasquez_fuentes_vegetacion_2008] usan coeficientes de correlación entre los pares de variables ambientales y socioeconómicas agregadas en unidades censales o administrativas para luego usar modelos de regresión de lineal con el fin de estimar la importancia explicativa de las variables a través de la estimación de los coeficientes. 

@tratalos_urban_2007 indaga sobre relaciones entre indicadores ambientales y el estatus social de los residente en cinco ciudades del Reino Unido; se usa coeficientes de correlación de Spearman para seleccionar las variables usadas en un modelo de regresión lineal usando OLS para probar que los desarrollos urbanos de alta densidad generalmente se asociaban con un pobre desempeño ambiental, medido por el tamaño del parche en el espacio verde y los niveles de provisión de servicios ambientales. 

### Enfoque geoestadístico

Cuando se analiza el resultado de los residuos $e_i$ debería ser ruido. Sin embargo si se encuentra que existe algún tipo de relación de los residuos con la posición de las observaciones $i$ en plano geográfico, entonces se puede usar variaciones en el modelo lineal, que coniste en incluir un término lineal usando la variable dependiente (modelo autoregresivo SAR, ecuación \@ref(eq:sar)) , las independientes ( spatial lag o retardo espacial en $X$ SLX, ecuación \@ref(eq:slx)), en el error (modelo espacial del errore SEM,ecuación \@ref(eq:sem)) o usando una combinacion del modelo de error y autoregresivo (modelo espacial de Durbin SD,ecuación \@ref(eq:sd)). Todas estas aproximaciones introducen una matriz de $W_{n\times n}$, donde $n$ es el número de sitios, que captura la influencia de las variables en relación con su proximidad. 

Esto significa que se propone a priori una relación espacial al dar estructura a $W$, por ejemplo usando solo valores de 1 (vecino) y 0 (no vecino) a las unidades espaciales contiguas o expresa una relación global usando una métrica de distancia en los valores de la matriz $W$, por ejemplo $w_{ij}= 1/d_{ij}$  donde $d_{ij}$ es la distancia euclidiana entre los centroides de los sitios $i$ y $j$ . La idea es que los vecinos más cercanos influencian más la unidad $i$, basados en la primera ley de la geografía o Ley de Tobler^["Todas las cosas están relacionadas entre sí, pero las cosas más próximas en el espacio tienen una relación mayor que las distantes."] [@tobler1970computer]. Este es un supuesto fuerte, y debe ser coherente con el fenómeno y los datos que lo representan. Justamente con la matriz $W$ se calcula el coeficiente de Moran’I [@moran1950notes], que se usa para probar una asociación global entre una variable y su posición en el plano. Si los residuos  $e_i$ muestran una asociación fuerte con la estructura de $W$ en la prueba de Moran’I, se sugiere usar alguno de los modelos espaciales (SAR,SLX,SEM o SD), pues esto significa que no se puede confiar en los coeficientes estimados por la regresión lineal. Se aduce que $W$ puede ayudar a explicar el proceso que se está modelando. De lo contrario es mejor usar un modelo lineal u otra técnica. [@paez_spatial_2005; @kissling_spatial_2008; @anselin_under_2002] hacen una revisión de los procesos espaciales, sus supuesto y los criterios de ajuste como errores cuadráticos y criterio de información de Akaike para la selección de un modelo y diseño bien formulado y ajustado.

Modelo espacial autoregresivo (SAR)
\begin{equation}
Y=X\mathbf{\beta}+\mathbf{\rho}WY+e
(\#eq:sar)
\end{equation}

Modelo de error espacial (SEM)
\begin{equation}
Y=X\mathbf{\beta}+u \\
u=\mathbf{\rho}Wu+e
(\#eq:sem)
\end{equation}

Modelo de retardo espacial en los terminos independiente (SLX)
\begin{equation}
Y=X\mathbf{\beta}+WX\mathbf{\lambda}+e
(\#eq:slx)
\end{equation}

Modelo espacial de Durbin SD
\begin{equation}
Y=X\mathbf{\beta}+\mathbf{\rho}WY+WX\mathbf{\lambda}+e
(\#eq:sd)
\end{equation}

>Para la escogencia del modelo más apropiado para corregir la estimación del OLS se usa frecuentemente el test de los multiplicadores de Lagrange y tanto para el modelo SAR coomo el SEM. (Mejorar la explicacion de los criterios de ajuste y de seleccion del modelo ara evitar una mal especificacion ....por completar) 

Estudios como [@landry_street_2009; @schwarz_trees_2015; @zhou_social_2013; @shanahan_socio-economic_2014] hacen uso de modelos autorregresivos y de retardo espacial para explicar los errores en el modelo lineal y mejorar el ajuste comparando modelos que relacionan de las variables ambientales(cobertura de copa y acceso a EV) con indicadores socioeconómicos.

Sin embargo trabajos como [@lesage_biggest_2014; @kissling_spatial_2008;Gibbons & Overman, 2012] hacen una crítica muy relevante a esta aproximación, y muestran que la inclusión de los términos de auto regresión (SAR) no aportan mucho, pues existe un acople entre los estimadores de los coeficientes que le quita peso a la posibilidad de interpretar los coeficientes como factores del efecto aislado de uno de las variables explicativas. Además, muestra que el ajuste no suele ser muy sensible a variaciones en W, lo que derrumba un poco la idea de importancia de la vecindad definida a priori. [@lesage_biggest_2014] propone que si la meta de usar modelos de regresión espacial es tener aproximadamente medidas escalares correctas de resumen de los efectos directos, indirectos y totales sobre la variable dependiente que surgen de cambios en las variables explicativas, entonces si parece bastante factible que se usen estos modelos [@lesage_biggest_2014]. 

Además del uso del análisis de autocorrelación espacial global, se puede explorar métodos que hacen análisis local de la variabilidad y sensibilidad de los parámetros usados para las estimaciones OLS. Si no hay autocorrelación global o ninguna agrupación, todavía podemos encontrar grupos a nivel local utilizando autocorrelación espacial local. El hecho de que de la Morán I es una suma de productos cruzados individuales es explotado por los "indicadores locales de asociación espacial" (LISA) para evaluar la agrupación de las unidades individuales mediante el cálculo del índice de Moran local para cada unidad espacial y la evaluación de la significación estadística p-value para cada sitio i [@talen_assessing_1998]. En @fotheringham_geographically_1998 se muestra que la regresión geográficamente ponderada (Geographically weighted regression GWR) produce resultados más informativos con respecto a la variación de parámetros en el espacio que la simple utilización de los agregados estadísticos. Estos métodos puede ser utilizado para examinar visualmente la variabilidad espacial de los resultados de la regresión o de las variables del estudio a través de una región y así informar sobre la presencia de no-estacionariedad espacial. La GWR es usada con éxito en [@comber_spatial_2011] para analizar los posibles factores que pueden ayudar a identificar y caracterizar las dimensiones a tener en cuenta para mejorar el acceso a la salud. 

### Otras técnicas

[@nesbitt_exploring_2016] investigan la relación de usos de suelo para establecer diferencias entre las coberturas usando análisis de varianza (ANOVA).  En [@kabisch_green_2014] se usa el análisis cluster para identificar grupos de población con características socioeconómicas similares y similar acceso a espacios verdes, para luego analizar si existen diferencias entre la distribución de los espacios verdes usando el coeficiente de Gini para diferentes grupos de población definidos en un tipo de análisis de disimilitud.	
